services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pedidos_db
      DB_PORT: 5432
  database:
    build:
      context: .
      dockerfile: sql/Dockerfile 
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  wso2:
    image: wso2/wso2ei-integrator:6.4.0
    ports:
      - '9443:9443'
    depends_on:
      - backend

volumes:
  postgres-data: